- name: Add GPG key
  become: true
  apt_key:
    url: "https://packages.grafana.com/gpg.key"

- name: Add repository for OSS version
  become: true
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present

- name: Install grafana packages
  become: true
  apt:
    pkg: 
      - gnupg
      - software-properties-common
      - apt-transport-https
      - grafana
    state: present
    update_cache: yes

- name: Copy grafana datasource file
  become: true
  copy:
    src: grafana_datasource.yaml
    dest: /etc/grafana/provisioning/datasources/prometheus.yaml
    mode: '0644'
  notify: Restart grafana-server service

- name: Copy grafana dashboard JSON file
  become: true
  copy:
    src: geth_dashboard.json
    dest: /etc/grafana/provisioning/dashboards/geth_dashboard.json
    mode: '0644'

- name: Copy grafana dashboard provider file
  become: true
  copy:
    src: geth_dashboard_provider.yaml
    dest: /etc/grafana/provisioning/dashboards/geth_provider.yaml
    mode: '0644'
  notify: Restart grafana-server service

- name: Start grafana service
  become: true
  systemd:
    name: grafana-server
    enabled: true
    state: started
    daemon_reload: true